### PR TITLE
Zendframework1

### PR DESCRIPTION
**Pull request by madeindjs**
Bonjour @Grafikart !

I had to learn **ZendFramework 1.12** in few weeks. I thought it will be a good idea to build a BlogMVC app and include it in your project.

I hope it will help someone.

Best regards.

PS: I love your videos on [Graphikart.fr](https://www.grafikart.fr/)

### CODE REVIEW

**Comment by Grafikart** [comment]
Thanks but there is a lots of file here. Could you load zend through composer to include only your code (and not the full framework)

**Comment by madeindjs** [comment]
Sorry, I forget to remove it.
I corrected it and I added instructions to setup ZendFramework1 project.

**Comment by CaporalDead** [comment]
Hi @madeindjs , you should definitly pull zf12 from composer, there's an official repository. I'll update your PR.

**Comment by CaporalDead** [comment]
@madeindjs PR done https://github.com/madeindjs/BlogMVC/pull/1

**Comment by CaporalDead** [comment]
You should also choose to stick on Zf1 class naming convention or use full psr4 namespace convention. eg : 

* controllers/AdminController.php > AdminController
* models/DbTable/Categories.php > Application_Model_DbTable_Categories

Snake case was used by Zend when PHP did not support namespacing, but composer can autoload those classes using psr4. The choice is yours :).

Everything seems to be ok. I can look more deeply if you want.

**Comment by madeindjs** [comment]
I merged @CaporalDead's fork. I think you can now merge this fork :)

**Comment by Grafikart** [comment]
Could you host it on your own repository. I plan to use git submodule to manage the frameworks (so ppl doesn't have to pull the whole history on clone) ?

**Comment by madeindjs** [comment]
OK no problems ;)

**Pull request closed without merging**
